name: FirstPlugin
version: '${project.version}'
main: tech.codemein.firstplugin.FirstPlugin
api-version: 1.20
commands:
  hello:
    aliases: [hi]
    usage: /hello
    description: "Simple minecraft command"
